### PR TITLE
Add support for closed paths on the measure layer

### PR DESCRIPTION
**Pull request by aivazis**
The measure layer currently allows the user to form a path from a collection of selected points on the measure layer. This path can be sent to the server to obtain the data values along the path in a CSV file. The same mechanism can be deployed to form a closed region with the intent of instructing the server to generate arbitrary, data product specific information about the signal within the closed region.

This PR adds a mechanism for toggling whether the path of points is closed and to record this information for each active viewport. The resulting region is not tested for any properties, such as convexity, that might be required for specific purposes. It is expected that such tests, as appropriate, will be performed by the server when generating responses.

### CODE REVIEW

**Review by parosen — APPROVED** [review]
Nice solution to the path closure problem.

**Comment by parosen** [comment]
I discovered that the CSV file does not list the points on the segment from the last path node back to the origin when the path his closed.

**Comment by aivazis** [comment]
oops. i'll take care of it asap

**Comment by aivazis** [comment]
Addressed in ac30e8b1e8d5438342560bc6d8460393cf85b4c0 .. df4ed01f72f583d037d8bd2ac8711d7ab0b1c871

**Comment by aivazis** [comment]
For the record, since this PR is closed and the associated branch has been deleted, the commits with the fix are in the `main` branch

**Pull request merged**
